function patches = dcp_extract(dicovery_set, world_set_filename)
% param1: discovery_set: discovery image set. The images from which
%         discriminative patches should be extracted organised as cell
%         array (different resolutions between the images are allowed)
% param2: world_set_filename: filename as string of the initially generated
%         "natural world set". If not given, the default filename
%         'world_set.mat' is used. A natural world set can be generated by
%         executing 'dcp_generate_world_set.m'
% return: The extracted most discriminative patches organised as cell array
% 
% Before calling this function, make sure that a valid world set data file
% (default 'world_set.mat') is present.
% Otherwise generate it by executing 'dcp_generate_world_set.m' once

% Initial steps

patches = 0;