function patches = dcp_extract(params, dicovery_set, world_set)
% param1: discovery_set: discovery image set. The images from which
%         discriminative patches should be extracted organised as cell
%         array (different resolutions between the images are allowed)
% param2: world_set: HOG-Descriptor array of the initially generated
%         "natural world set". A natural world set can be generated by
%         executing 'dcp_generate_world_set.m'
% return: The extracted most discriminative patches organised as cell array
% 
% Before calling this function, make sure that a valid world set is present.
% Otherwise generate it by executing 'dcp_generate_world_set.m' once

% Initial steps

patches = 0;